<script>var t=setTimeout("gs.reloadQueue()", 15000);</script>
<div id='song_list' class='queue'>
	{loop="$queue"}
	<div class='row-fluid item_song item_listitem {$value.priority} {$value.status} {$value.token}' onclick=''>
		<div class='col-lg-12'>
			<div class='item_status'></div>
			<div class='song_name'>{$value.title}</div>
			<div class='song_artist'>{$value.artist}</div>
			<div class='song_played_by'>{$value.played_by_name}</div>
	
			{if="$value.status == 'playing'"}
			<span class='label label-info now_playing_marker'>now playing</span>
			{elseif="$value.priority == 'high'"}
			<span class='label label-success high_priority_marker'>promoted</span>
			{/if}
		</div>
	</div>
	{else}
	<div class="queue_empty">no songs</div>
	{/loop}
</div>