<input type='hidden' value='default' id='session_name'  maxlength='32' />
<input type='hidden' id='session_id' />
<div class='row-fluid nickview_row'>
	<div class='col-lg-12'>
		<div class='setUser_header'>enter your name</div>
	</div>
</div>
<div class='row-fluid nickview_row'>
	<div class='col-lg-12 setUser_textbox'>
		<input type='text' class='input-lg cookie_nickname' id='setUser_textbox' placeholder='name' maxlength='32' />
	</div>
</div>
<div class='row-fluid nickview_row'>
	<div class='col-lg-12 nickview_submit'>
		<div id='setUser_submit' class='btn btn-lg btn-default' onclick=''>submit</div>
	</div>
</div>
