<div id='song_list' class='search'>
	{loop="$results"}
	<div class='row-fluid item_song item_search' rel='{$value.SongID}' onclick=''>
		<div class='col-lg-12 songinfo'>
					<div class='song_name'>{$value.SongName}</div>
					<div class='song_artist'>{$value.ArtistName}</div>
					<div class='song_id'>{$value.SongID}</div>
		</div>
		<div class='col-lg-12 moreoptions'>
			<div class='addToQueue_cont' style='margin-left: -3px;'>
				<div class='addToQueue addToQueue_promote btn btn-warning' onclick=''>promote</div>
			</div>
			<div class='addToQueue_cont'>
				<div class='addToQueue addToQueue_add btn btn-success' onclick=''>add to queue</div>
			</div>
			<div class='clearfloat'></div>
		</div>
	</div>
	{else}
	<div id='error_message_generic'>No Results Found</div>
	{/loop}
</div>
<div style="clear: both;"></div><div class="navbar navbar-fixed-bottom">
	<div class="row-fluid" id="backToQueue_options">
		<div class="col-lg-12">
			<div id="button_queue" class="btn btn-info" onclick="">back to queue</div>
		</div>
	</div>
</div>



